// ========================================
// DriveEase — Mock Data
// ========================================

const CITIES = [
  { id: 'bangalore', name: 'Bangalore', emoji: '🏙️', count: 450 },
  { id: 'mumbai', name: 'Mumbai', emoji: '🌊', count: 380 },
  { id: 'delhi', name: 'Delhi', emoji: '🕌', count: 520 },
  { id: 'chennai', name: 'Chennai', emoji: '🛕', count: 290 },
  { id: 'hyderabad', name: 'Hyderabad', emoji: '🏰', count: 340 },
  { id: 'pune', name: 'Pune', emoji: '⛰️', count: 270 },
  { id: 'kolkata', name: 'Kolkata', emoji: '🌉', count: 210 },
  { id: 'goa', name: 'Goa', emoji: '🏖️', count: 180 },
];

const CAR_FEATURES = {
  ac: { icon: '❄️', name: 'Air Conditioning' },
  bluetooth: { icon: '📶', name: 'Bluetooth' },
  gps: { icon: '📍', name: 'GPS Navigation' },
  usb: { icon: '🔌', name: 'USB Charging' },
  sunroof: { icon: '☀️', name: 'Sunroof' },
  camera: { icon: '📷', name: 'Rear Camera' },
  cruise: { icon: '🚀', name: 'Cruise Control' },
  keyless: { icon: '🔑', name: 'Keyless Entry' },
  airbag: { icon: '🛡️', name: 'Airbags' },
  abs: { icon: '🔒', name: 'ABS' },
  parking: { icon: '🅿️', name: 'Parking Sensors' },
  android: { icon: '📱', name: 'Android Auto' },
  apple: { icon: '🍎', name: 'Apple CarPlay' },
  music: { icon: '🎵', name: 'Premium Audio' },
  leather: { icon: '💺', name: 'Leather Seats' },
};

const CARS = [
  {
    id: 1,
    name: 'Swift Dzire',
    brand: 'Maruti Suzuki',
    year: 2024,
    type: 'sedan',
    transmission: 'manual',
    fuel: 'petrol',
    seats: 5,
    mileage: '22 km/l',
    pricePerHour: 149,
    pricePerDay: 1499,
    rating: 4.5,
    reviews: 234,
    city: 'bangalore',
    features: ['ac', 'bluetooth', 'usb', 'camera', 'airbag', 'abs'],
    image: '',
    emoji: '🚗',
    color: '#3b82f6',
    trips: 890,
    host: { name: 'Rahul K.', rating: 4.8, trips: 340 },
    available: true,
    description: 'The Maruti Suzuki Swift Dzire is a compact sedan perfect for city drives and short trips. Excellent fuel economy and comfortable interiors make it an ideal choice.',
  },
  {
    id: 2,
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    year: 2025,
    type: 'suv',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 5,
    mileage: '18 km/l',
    pricePerHour: 249,
    pricePerDay: 2499,
    rating: 4.7,
    reviews: 456,
    city: 'mumbai',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple'],
    image: '',
    emoji: '🚙',
    color: '#8b5cf6',
    trips: 1250,
    host: { name: 'Priya M.', rating: 4.9, trips: 520 },
    available: true,
    description: 'The Hyundai Creta is a feature-packed SUV with a panoramic sunroof, advanced ADAS features, and a powerful diesel engine. Perfect for highway adventures.',
  },
  {
    id: 3,
    name: 'Tata Nexon EV',
    brand: 'Tata',
    year: 2025,
    type: 'suv',
    transmission: 'automatic',
    fuel: 'electric',
    seats: 5,
    mileage: '312 km range',
    pricePerHour: 299,
    pricePerDay: 2799,
    rating: 4.6,
    reviews: 189,
    city: 'bangalore',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'camera', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music'],
    image: '',
    emoji: '⚡',
    color: '#06d6a0',
    trips: 670,
    host: { name: 'Amit S.', rating: 4.7, trips: 280 },
    available: true,
    description: 'The Tata Nexon EV Max is India\'s most popular electric SUV with a 312 km range, fast charging, and zero emissions. The future of driving is here.',
  },
  {
    id: 4,
    name: 'Honda City',
    brand: 'Honda',
    year: 2024,
    type: 'sedan',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '18 km/l',
    pricePerHour: 199,
    pricePerDay: 1899,
    rating: 4.4,
    reviews: 312,
    city: 'delhi',
    features: ['ac', 'bluetooth', 'usb', 'camera', 'cruise', 'airbag', 'abs', 'android', 'apple', 'music'],
    image: '',
    emoji: '🚘',
    color: '#f59e0b',
    trips: 1100,
    host: { name: 'Sneha R.', rating: 4.6, trips: 410 },
    available: true,
    description: 'The Honda City is a premium sedan known for its refined driving experience, spacious cabin, and advanced safety features. A true driver\'s car.',
  },
  {
    id: 5,
    name: 'Mahindra Thar',
    brand: 'Mahindra',
    year: 2024,
    type: 'suv',
    transmission: 'manual',
    fuel: 'diesel',
    seats: 4,
    mileage: '15 km/l',
    pricePerHour: 349,
    pricePerDay: 3299,
    rating: 4.8,
    reviews: 567,
    city: 'goa',
    features: ['ac', 'bluetooth', 'usb', 'camera', 'keyless', 'airbag', 'abs'],
    image: '',
    emoji: '🛻',
    color: '#ef4444',
    trips: 1450,
    host: { name: 'Vikram P.', rating: 4.9, trips: 680 },
    available: true,
    description: 'The Mahindra Thar is an iconic off-road SUV perfect for adventure seekers. With 4x4 capability and rugged design, it\'s built for the wild.',
  },
  {
    id: 6,
    name: 'Maruti Baleno',
    brand: 'Maruti Suzuki',
    year: 2024,
    type: 'hatchback',
    transmission: 'manual',
    fuel: 'petrol',
    seats: 5,
    mileage: '24 km/l',
    pricePerHour: 129,
    pricePerDay: 1199,
    rating: 4.3,
    reviews: 198,
    city: 'chennai',
    features: ['ac', 'bluetooth', 'usb', 'camera', 'airbag', 'abs', 'android'],
    image: '',
    emoji: '🚗',
    color: '#10b981',
    trips: 760,
    host: { name: 'Kumar V.', rating: 4.5, trips: 220 },
    available: true,
    description: 'The Maruti Baleno is a premium hatchback with sporty design, excellent fuel economy, and a spacious cabin. Ideal for daily city commuting.',
  },
  {
    id: 7,
    name: 'Toyota Fortuner',
    brand: 'Toyota',
    year: 2024,
    type: 'suv',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    mileage: '14 km/l',
    pricePerHour: 499,
    pricePerDay: 4499,
    rating: 4.9,
    reviews: 678,
    city: 'delhi',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music', 'leather'],
    image: '',
    emoji: '🏎️',
    color: '#1e293b',
    trips: 2100,
    host: { name: 'Rajesh G.', rating: 5.0, trips: 890 },
    available: true,
    description: 'The Toyota Fortuner is the king of SUVs. With a commanding road presence, powerful diesel engine, and premium interiors, it\'s the ultimate road trip companion.',
  },
  {
    id: 8,
    name: 'Kia Seltos',
    brand: 'Kia',
    year: 2025,
    type: 'suv',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '16 km/l',
    pricePerHour: 229,
    pricePerDay: 2199,
    rating: 4.5,
    reviews: 345,
    city: 'hyderabad',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music'],
    image: '',
    emoji: '🚙',
    color: '#6366f1',
    trips: 980,
    host: { name: 'Deepa N.', rating: 4.7, trips: 390 },
    available: true,
    description: 'The Kia Seltos is a stylish and tech-loaded SUV with ADAS Level 2 features, a panoramic sunroof, and a premium Bose sound system.',
  },
  {
    id: 9,
    name: 'Tata Punch',
    brand: 'Tata',
    year: 2024,
    type: 'hatchback',
    transmission: 'manual',
    fuel: 'petrol',
    seats: 5,
    mileage: '20 km/l',
    pricePerHour: 119,
    pricePerDay: 999,
    rating: 4.2,
    reviews: 156,
    city: 'pune',
    features: ['ac', 'bluetooth', 'usb', 'airbag', 'abs'],
    image: '',
    emoji: '🚗',
    color: '#f97316',
    trips: 540,
    host: { name: 'Neha T.', rating: 4.4, trips: 160 },
    available: true,
    description: 'The Tata Punch is a micro SUV with 5-star safety rating, peppy performance, and bold design. Budget-friendly without compromising on safety.',
  },
  {
    id: 10,
    name: 'MG Hector',
    brand: 'MG',
    year: 2024,
    type: 'suv',
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    mileage: '17 km/l',
    pricePerHour: 279,
    pricePerDay: 2599,
    rating: 4.4,
    reviews: 234,
    city: 'mumbai',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music'],
    image: '',
    emoji: '🚙',
    color: '#dc2626',
    trips: 780,
    host: { name: 'Arun D.', rating: 4.6, trips: 310 },
    available: true,
    description: 'The MG Hector is India\'s first internet car with a 14-inch infotainment screen, hybrid powertrain, and spacious 7-seater option.',
  },
  {
    id: 11,
    name: 'BMW 3 Series',
    brand: 'BMW',
    year: 2024,
    type: 'luxury',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '15 km/l',
    pricePerHour: 799,
    pricePerDay: 6999,
    rating: 4.9,
    reviews: 123,
    city: 'bangalore',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music', 'leather'],
    image: '',
    emoji: '🏎️',
    color: '#1e40af',
    trips: 340,
    host: { name: 'Sanjay M.', rating: 5.0, trips: 120 },
    available: true,
    description: 'The BMW 3 Series Gran Limousine is the ultimate driving machine. Experience luxury, performance, and cutting-edge technology in this premium sedan.',
  },
  {
    id: 12,
    name: 'Mercedes C-Class',
    brand: 'Mercedes-Benz',
    year: 2024,
    type: 'luxury',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '14 km/l',
    pricePerHour: 899,
    pricePerDay: 7999,
    rating: 4.9,
    reviews: 98,
    city: 'delhi',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music', 'leather'],
    image: '',
    emoji: '✨',
    color: '#7c3aed',
    trips: 280,
    host: { name: 'Kavita L.', rating: 5.0, trips: 95 },
    available: true,
    description: 'The Mercedes-Benz C-Class sets the benchmark for luxury sedans with its MBUX infotainment system, ambient lighting, and refined ride quality.',
  },
  {
    id: 13,
    name: 'Royal Enfield Himalayan',
    brand: 'Royal Enfield',
    year: 2025,
    type: 'suv',
    transmission: 'manual',
    fuel: 'petrol',
    seats: 5,
    mileage: '20 km/l',
    pricePerHour: 179,
    pricePerDay: 1699,
    rating: 4.3,
    reviews: 167,
    city: 'goa',
    features: ['ac', 'bluetooth', 'usb', 'airbag', 'abs'],
    image: '',
    emoji: '🚗',
    color: '#84cc16',
    trips: 430,
    host: { name: 'Arjun S.', rating: 4.5, trips: 180 },
    available: true,
    description: 'A reliable and rugged vehicle perfect for exploring Goa\'s scenic routes. Great fuel economy and comfortable for long drives.',
  },
  {
    id: 14,
    name: 'Volkswagen Virtus',
    brand: 'Volkswagen',
    year: 2024,
    type: 'sedan',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '18 km/l',
    pricePerHour: 219,
    pricePerDay: 2099,
    rating: 4.5,
    reviews: 201,
    city: 'pune',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'music'],
    image: '',
    emoji: '🚘',
    color: '#0891b2',
    trips: 620,
    host: { name: 'Meera J.', rating: 4.7, trips: 250 },
    available: true,
    description: 'The Volkswagen Virtus is a German-engineered sedan with a turbocharged engine, premium interiors, and rock-solid build quality.',
  },
  {
    id: 15,
    name: 'Hyundai i20',
    brand: 'Hyundai',
    year: 2024,
    type: 'hatchback',
    transmission: 'manual',
    fuel: 'petrol',
    seats: 5,
    mileage: '21 km/l',
    pricePerHour: 139,
    pricePerDay: 1299,
    rating: 4.4,
    reviews: 278,
    city: 'kolkata',
    features: ['ac', 'bluetooth', 'usb', 'camera', 'airbag', 'abs', 'android', 'apple'],
    image: '',
    emoji: '🚗',
    color: '#e11d48',
    trips: 820,
    host: { name: 'Suresh B.', rating: 4.6, trips: 340 },
    available: true,
    description: 'The Hyundai i20 is a stylish premium hatchback with sporty design, connected car tech, and a peppy turbo engine option.',
  },
  {
    id: 16,
    name: 'Audi Q5',
    brand: 'Audi',
    year: 2025,
    type: 'luxury',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '12 km/l',
    pricePerHour: 999,
    pricePerDay: 8999,
    rating: 4.8,
    reviews: 67,
    city: 'mumbai',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music', 'leather'],
    image: '',
    emoji: '🏎️',
    color: '#0f172a',
    trips: 190,
    host: { name: 'Ritu K.', rating: 5.0, trips: 65 },
    available: true,
    description: 'The Audi Q5 is a luxury SUV that blends performance with elegance. Quattro all-wheel drive, virtual cockpit, and premium Matrix LED headlights.',
  },
  {
    id: 17,
    name: 'Tata Harrier',
    brand: 'Tata',
    year: 2024,
    type: 'suv',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 5,
    mileage: '16 km/l',
    pricePerHour: 259,
    pricePerDay: 2399,
    rating: 4.5,
    reviews: 298,
    city: 'hyderabad',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music'],
    image: '',
    emoji: '🚙',
    color: '#059669',
    trips: 870,
    host: { name: 'Pooja S.', rating: 4.6, trips: 350 },
    available: true,
    description: 'The Tata Harrier is a premium SUV built on the Land Rover D8 platform. Commanding road presence and feature-rich cabin at a great price.',
  },
  {
    id: 18,
    name: 'Skoda Slavia',
    brand: 'Skoda',
    year: 2024,
    type: 'sedan',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '19 km/l',
    pricePerHour: 199,
    pricePerDay: 1799,
    rating: 4.3,
    reviews: 178,
    city: 'chennai',
    features: ['ac', 'bluetooth', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'android'],
    image: '',
    emoji: '🚘',
    color: '#4338ca',
    trips: 560,
    host: { name: 'Vinay R.', rating: 4.5, trips: 200 },
    available: true,
    description: 'The Skoda Slavia is a sporty sedan with a 1.5L TSI turbocharged engine, excellent handling, and a spacious boot. Pure driving pleasure.',
  },
  {
    id: 19,
    name: 'XUV700',
    brand: 'Mahindra',
    year: 2025,
    type: 'suv',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    mileage: '16 km/l',
    pricePerHour: 329,
    pricePerDay: 2999,
    rating: 4.7,
    reviews: 412,
    city: 'bangalore',
    features: ['ac', 'bluetooth', 'gps', 'usb', 'sunroof', 'camera', 'cruise', 'keyless', 'airbag', 'abs', 'parking', 'android', 'apple', 'music', 'leather'],
    image: '',
    emoji: '🚙',
    color: '#b91c1c',
    trips: 1340,
    host: { name: 'Anand M.', rating: 4.8, trips: 560 },
    available: true,
    description: 'The Mahindra XUV700 is a tech-loaded SUV with ADAS Level 2, flush door handles, dual HD displays, and a powerful mStallion engine.',
  },
  {
    id: 20,
    name: 'Innova Crysta',
    brand: 'Toyota',
    year: 2024,
    type: 'suv',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    mileage: '15 km/l',
    pricePerHour: 399,
    pricePerDay: 3599,
    rating: 4.8,
    reviews: 534,
    city: 'mumbai',
    features: ['ac', 'bluetooth', 'usb', 'camera', 'keyless', 'airbag', 'abs', 'music', 'leather'],
    image: '',
    emoji: '🚐',
    color: '#475569',
    trips: 1780,
    host: { name: 'Kiran P.', rating: 4.9, trips: 720 },
    available: true,
    description: 'The Toyota Innova Crysta is the gold standard for MPVs in India. Legendary reliability, spacious 7-seater cabin, and a smooth diesel engine.',
  },
];

const REVIEWS = [
  { id: 1, user: 'Aditi Sharma', avatar: 'AS', rating: 5, text: 'Amazing experience! The car was in perfect condition and the pickup was hassle-free. Will definitely use DriveEase again.', date: '2 days ago', carId: 2 },
  { id: 2, user: 'Mohit Verma', avatar: 'MV', rating: 4, text: 'Good service overall. The Creta was clean and drove well. Minor delay in pickup but nothing major.', date: '1 week ago', carId: 2 },
  { id: 3, user: 'Sneha Patel', avatar: 'SP', rating: 5, text: 'Loved the Nexon EV! Smooth, silent, and the range was more than enough for my weekend trip. Eco-friendly driving at its best.', date: '3 days ago', carId: 3 },
  { id: 4, user: 'Rohan Gupta', avatar: 'RG', rating: 5, text: 'The Mahindra Thar in Goa was an absolute blast! Perfect for beach drives and exploring off-road trails. 10/10 would recommend.', date: '5 days ago', carId: 5 },
  { id: 5, user: 'Priyanka Joshi', avatar: 'PJ', rating: 4, text: 'The BMW 3 Series was a dream to drive. Luxury feel without breaking the bank. DriveEase made it so easy.', date: '1 week ago', carId: 11 },
  { id: 6, user: 'Amit Reddy', avatar: 'AR', rating: 5, text: 'Rented the Fortuner for a family road trip. Spacious, comfortable, and the kids loved it. Best decision ever!', date: '4 days ago', carId: 7 },
  { id: 7, user: 'Kavya Singh', avatar: 'KS', rating: 4, text: 'Swift Dzire was perfect for my daily commute. Fuel efficient and easy to drive in city traffic. Great value for money.', date: '2 weeks ago', carId: 1 },
  { id: 8, user: 'Nikhil Rao', avatar: 'NR', rating: 5, text: 'Second time using DriveEase and both times have been excellent. The app is so intuitive and the cars are well maintained.', date: '6 days ago', carId: 8 },
  { id: 9, user: 'Divya Nair', avatar: 'DN', rating: 5, text: 'The XUV700 is a beast! All the tech features worked flawlessly. Cruise control on the highway was a lifesaver.', date: '1 week ago', carId: 19 },
  { id: 10, user: 'Saurabh Mishra', avatar: 'SM', rating: 4, text: 'Good selection of cars in Mumbai. The MG Hector hybrid was smooth and fuel efficient. Dashboard tech was impressive.', date: '3 days ago', carId: 10 },
  { id: 11, user: 'Tanvi Kulkarni', avatar: 'TK', rating: 5, text: 'Booked a Virtus for a Pune-Mumbai drive. German engineering at its finest! Stable at high speeds and great interiors.', date: '2 weeks ago', carId: 14 },
  { id: 12, user: 'Harsh Patel', avatar: 'HP', rating: 4, text: 'The Honda City never disappoints. Smooth automatic transmission and excellent mileage. Perfect sedan for any occasion.', date: '5 days ago', carId: 4 },
];

const ADDONS = [
  { id: 'insurance', name: 'Premium Insurance', description: 'Zero deductible, full coverage', icon: '🛡️', price: 299 },
  { id: 'child_seat', name: 'Child Seat', description: 'ISOFIX certified child seat', icon: '👶', price: 149 },
  { id: 'gps_device', name: 'GPS Device', description: 'Portable GPS navigation device', icon: '🗺️', price: 99 },
  { id: 'fuel_package', name: 'Fuel Package', description: 'Return car at any fuel level', icon: '⛽', price: 499 },
  { id: 'roadside', name: 'Roadside Assistance Plus', description: 'Priority 24/7 roadside help', icon: '🔧', price: 199 },
  { id: 'wifi', name: 'Mobile WiFi Hotspot', description: 'Stay connected on the go', icon: '📡', price: 149 },
];

// Export for use in modules
if (typeof window !== 'undefined') {
  window.AppData = { CITIES, CARS, CAR_FEATURES, REVIEWS, ADDONS };
}
